# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4b728e43932d6e826ad9e42f761884d6f8f2944e2447814c06cdcd613eac8aaba07576b4ac81766e8aeac89580741ee97961d1bef74d48e59d7f7e938200d5fd

test:
  secret_key_base: 3244dc1997af8d6b5527f3b4d962a418307d88a212c9490c7998522fac5e26ce9a6f71b38d6893c56756e34f5c7504a1b79ceb1b134ff63b045a216bab024c6b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
